# action.yml
name: 'Publish to Sharepoint'
description: 'Upload a file or tree to Sharepoint online'
author: 'Olivier Brassard, Daniel Monaghan, and Sky Syzygy'
branding:
  icon: 'upload-cloud'
  color: 'pink'
inputs:
  site_url:
    description: 'The Sharepoint site url'
    required: true
  sharepoint_client_id:
    description: 'Client ID to use for authentication'
    required: false
  sharepoint_client_secret:
    description: 'Client Secret to use for authentication'
    required: false
  sharepoint_username:
    description: 'Username to use for authentication'
    required: false
  sharepoint_password:
    description: 'Password to use for authentication'
    required: false
  library_folder:
    description: 'The path where to upload the files in the library'
    required: true
    default: "Shared documents"
  glob:
    description: "Filenames to upload to SharePoint. string or string array, i.e. 'build/css/style.css' or ['build/css/*.*']."
    required: false
  base:
    description: "Base directory, if you want to preserve folders structure inside Sharepoint folder, you can provide a base for you files. For example when using glob ['build/css/*.*'] and base: 'build', all css files will be loaded under [SharePoint folder]/css"
    required: false
  file_path:
    description: 'To upload a specific file instead of the whole repo, specify the path here'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
